# Generated by Django 4.1.2 on 2023-01-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listminer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='miner',
            name='id',
        ),
        migrations.AlterField(
            model_name='listminer',
            name='list_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='listminer',
            name='miner_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='miner',
            name='miner_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
