# Generated by Django 4.1.2 on 2023-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0004_alter_miner_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='miner',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
