# Generated by Django 4.1.2 on 2023-03-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0006_alter_miner_miner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='price_raw',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
