# Generated by Django 4.1.2 on 2023-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0007_miner_price_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='balance_human',
            field=models.FloatField(default=0),
        ),
    ]
