# Generated by Django 4.1.2 on 2023-07-01 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0010_miner_power_human_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miner',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
