# Generated by Django 4.1.2 on 2023-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0012_remove_order_price_order_balance_human_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='buyer',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
    ]
