# Generated by Django 4.1.2 on 2023-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0013_miner_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_hash',
            field=models.CharField(default='0x', max_length=66),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='balance_human',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='power_human',
            field=models.FloatField(default=0),
        ),
    ]
