# Generated by Django 4.1.2 on 2023-07-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0014_order_transaction_hash_alter_order_balance_human_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
