# Generated by Django 4.1.2 on 2023-07-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0015_alter_order_time_alter_order_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='is_submitted_transfer_out',
            field=models.BooleanField(default=False),
        ),
    ]
