# Generated by Django 4.1.2 on 2023-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0016_miner_is_submitted_transfer_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='miner',
            name='balance_human',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='miner',
            name='is_list',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='miner',
            name='list_time',
            field=models.BigIntegerField(db_index=True, default=1675156423),
        ),
        migrations.AlterField(
            model_name='miner',
            name='miner_id',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='miner',
            name='power_human',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='miner',
            name='price',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='order',
            name='miner_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
