# Generated by Django 4.1.2 on 2023-07-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spex', '0018_minerprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinerLastInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_id', models.IntegerField(unique=True)),
                ('price_human', models.FloatField()),
                ('owner', models.CharField(max_length=42)),
                ('buyer', models.CharField(max_length=42)),
                ('balance_human', models.FloatField()),
                ('power_human', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='miner',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
