# Generated by Django 4.1.2 on 2023-01-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_id', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=42)),
                ('price', models.IntegerField()),
                ('list_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_id', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=42)),
            ],
        ),
    ]
