# Generated by Django 4.1.2 on 2023-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("miner_total_balance_human", models.FloatField(default=0)),
                ("daily_interest_rate", models.FloatField(default=0)),
                ("annual_interest_rate", models.FloatField(default=0)),
                ("current_principal_human", models.FloatField(default=0)),
                ("total_interest_human", models.FloatField(default=0)),
                (
                    "last_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("last_amount_human", models.FloatField(default=0)),
                ("last_update_timestamp", models.BigIntegerField(default=1675156423)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Miner",
            fields=[
                (
                    "miner_id",
                    models.BigIntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("delegator_address", models.CharField(max_length=42)),
                (
                    "max_debt_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("max_debt_amount_human", models.FloatField(db_index=True, default=0)),
                ("receive_address", models.CharField(max_length=42)),
                ("annual_interest_rate_human", models.FloatField(default=0)),
                (
                    "last_debt_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("last_debt_amount_human", models.FloatField(default=0)),
                ("last_update_timestamp", models.BigIntegerField(default=1675156423)),
                ("disabled", models.BooleanField(default=False)),
                ("collateral_rate", models.FloatField(default=0)),
                ("total_balance_human", models.FloatField(default=0)),
                ("available_balance_human", models.FloatField(default=0)),
                ("initial_pledge_human", models.FloatField(default=0)),
                ("locked_rewards_human", models.FloatField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SellItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField(default=0)),
                ("price_raw", models.CharField(blank=True, default="0", max_length=80)),
                ("price_human", models.FloatField(default=0)),
                ("last_update_timestamp", models.BigIntegerField(default=1675156423)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
    ]
