# Generated by Django 4.1.13 on 2023-12-11 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("annual_interest_rate_human", models.FloatField(default=0)),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField()),
                ("time", models.DateTimeField(db_index=True)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanOperatorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("operator_user_address", models.CharField(max_length=42)),
                (
                    "operator_type",
                    models.CharField(
                        choices=[
                            ("lend", "lend"),
                            ("wallet_repayment", "wallet_repayment"),
                            ("withdraw_repayment", "withdraw_repayment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField()),
                ("time", models.DateTimeField(db_index=True)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Miner",
            fields=[
                (
                    "miner_id",
                    models.BigIntegerField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                ("delegator_address", models.CharField(max_length=42)),
                (
                    "max_debt_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("max_debt_amount_human", models.FloatField(db_index=True, default=0)),
                ("receive_address", models.CharField(max_length=42)),
                ("annual_interest_rate_human", models.FloatField(default=0)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "principal_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("principal_amount_human", models.FloatField(default=0)),
                ("max_lender_count", models.IntegerField(default=0)),
                (
                    "min_lend_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("min_lend_amount_human", models.FloatField(default=0)),
                ("collateral_rate", models.FloatField(default=0)),
                ("total_balance_human", models.FloatField(default=0)),
                ("available_balance_human", models.FloatField(default=0)),
                ("initial_pledge_human", models.FloatField(default=0)),
                ("locked_rewards_human", models.FloatField(default=0)),
                (
                    "last_list_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed", models.BooleanField(default=False)),
                ("current_total_debt_human", models.FloatField(default=0)),
                ("current_total_principal_human", models.FloatField(default=0)),
                ("current_total_interest_human", models.FloatField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaybackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField()),
                ("time", models.DateTimeField(db_index=True)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SellItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField(default=0)),
                ("price_raw", models.CharField(blank=True, default="0", max_length=80)),
                ("price_human", models.FloatField(default=0)),
                ("last_update_timestamp", models.BigIntegerField(default=1675156423)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("miner_total_balance_human", models.FloatField(default=0)),
                ("daily_interest_rate", models.FloatField(default=0)),
                ("annual_interest_rate", models.FloatField(default=0)),
                (
                    "current_principal_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("current_principal_human", models.FloatField(default=0)),
                ("current_interest_human", models.FloatField(default=0)),
                ("current_total_amount_human", models.FloatField(default=0)),
                (
                    "last_amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("last_amount_human", models.FloatField(default=0)),
                ("last_update_timestamp", models.BigIntegerField(default=1675156423)),
                ("transaction_hash", models.CharField(max_length=68)),
                ("completed", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("miner_id", "user_address")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=42)),
                ("content", models.TextField(max_length=100)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.miner"
                    ),
                ),
            ],
        ),
    ]
