# Generated by Django 4.1.13 on 2023-12-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='daily_interest_rate',
        ),
    ]
