# Generated by Django 4.1.2 on 2023-10-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="transaction_hash",
            field=models.CharField(default="0x00", max_length=66),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=42)),
                ("content", models.TextField(max_length=100)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.miner"
                    ),
                ),
            ],
        ),
    ]
