# Generated by Django 4.1.2 on 2023-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0002_loan_transaction_hash_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("annual_interest_rate", models.FloatField(default=0)),
                ("amount_human", models.FloatField()),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaybackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("amount_human", models.FloatField()),
                ("interest_human", models.FloatField()),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
