# Generated by Django 4.1.2 on 2023-10-16 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0003_loanitem_paybackitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together={("miner_id", "user_address")},
        ),
    ]
