# Generated by Django 4.1.2 on 2023-10-18 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0004_alter_loan_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanOperatorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miner_id", models.BigIntegerField(db_index=True)),
                ("user_address", models.CharField(max_length=42)),
                ("operator_user_address", models.CharField(max_length=42)),
                (
                    "operator_type",
                    models.CharField(
                        choices=[
                            ("lend", "lend"),
                            ("wallet_repayment", "wallet_repayment"),
                            ("withdraw_repayment", "withdraw_repayment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "amount_raw",
                    models.CharField(blank=True, default="0", max_length=80),
                ),
                ("amount_human", models.FloatField()),
                ("time", models.DateTimeField(db_index=True)),
                ("create_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="loanitem",
            old_name="annual_interest_rate",
            new_name="annual_interest_rate_human",
        ),
        migrations.RemoveField(
            model_name="paybackitem",
            name="interest_human",
        ),
        migrations.AddField(
            model_name="loan",
            name="current_total_amount_human",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="current_total_amount_raw",
            field=models.CharField(blank=True, default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="loan",
            name="last_list_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="amount_raw",
            field=models.CharField(blank=True, default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="annual_interest_rate_raw",
            field=models.CharField(blank=True, default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paybackitem",
            name="amount_raw",
            field=models.CharField(blank=True, default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="paybackitem",
            name="time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
