# Generated by Django 4.1.2 on 2023-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0006_remove_loanitem_annual_interest_rate_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="last_list_time",
        ),
        migrations.AddField(
            model_name="loan",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="current_principal_raw",
            field=models.CharField(blank=True, default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="miner",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="miner",
            name="last_list_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
