# Generated by Django 4.1.2 on 2023-10-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0007_remove_loan_last_list_time_loan_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="miner",
            name="current_total_debt_human",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="miner",
            name="current_total_interest_human",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="miner",
            name="current_total_principal_human",
            field=models.FloatField(default=0),
        ),
    ]
