# Generated by Django 4.1.2 on 2023-10-20 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0008_miner_current_total_debt_human_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="total_interest_human",
            new_name="current_interest_human",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="current_principal_raw",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="current_total_amount_raw",
        ),
    ]
