# Generated by Django 3.2.15 on 2022-10-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
